[project]
name = "quant"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ccxt>=4.5.58",
    "ipykernel",
    "jupyter",
    "matplotlib",
    "numpy",
    "openpyxl",
    "pandas",
    "vectorbt>=0.28.2",
    "yfinance>=1.4.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.0",
]
