from __future__ import annotations

import json
from pathlib import Path

NOTEBOOK_PATH = Path("notebooks/bt_03.ipynb")

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# bt_03：真实 ETF 数据的 SMA 50/100/150/200/250 趋势跟踪参数区间测试\n",
            "\n",
            "本 notebook 使用东方财富公开 K 线接口下载后的真实 ETF 前复权日线数据：`data/real_etf_daily_eastmoney.csv`。\n",
            "\n",
            "目标不是挑一个收益最高的均线，而是检查 **50/100/150/200/250 这一段中长期 SMA 参数区间是否稳定**。\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 回测规则\n",
            "\n",
            "- 标的：创业板ETF、沪深300ETF、国债ETF\n",
            "- 数据：东方财富日线，前复权 `qfq`\n",
            "- 信号：`close > SMA(window)` 视为趋势偏强\n",
            "- 防未来函数：信号使用 `shift(1)`，即今天收盘确认信号，下一交易日才持仓\n",
            "- 成本：每次仓位变化扣 `0.1%`，粗略代表手续费 + 滑点\n",
            "- 对比：同时计算买入并持有基准\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from pathlib import Path\n",
            "\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "from matplotlib import font_manager\n",
            "\n",
            "# Set a Chinese-capable font so ETF names render correctly in plot titles.\n",
            "font_candidates = ['Microsoft YaHei', 'SimHei', 'Noto Sans CJK SC', 'Source Han Sans SC', 'Arial Unicode MS']\n",
            "available_fonts = {font.name for font in font_manager.fontManager.ttflist}\n",
            "for font_name in font_candidates:\n",
            "    if font_name in available_fonts:\n",
            "        plt.rcParams['font.sans-serif'] = [font_name, 'DejaVu Sans']\n",
            "        break\n",
            "plt.rcParams['axes.unicode_minus'] = False\n",
            "\n",
            "DATA_PATH = Path('../data/real_etf_daily_eastmoney.csv')\n",
            "WINDOWS = [50, 100, 150, 200, 250]\n",
            "FEE_RATE = 0.001\n",
            "TRADING_DAYS = 252\n",
            "\n",
            "pd.set_option('display.max_rows', 100)\n",
            "pd.set_option('display.float_format', lambda x: f'{x:,.4f}')\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "df = pd.read_csv(DATA_PATH, parse_dates=['date'], dtype={'symbol': 'string'})\n",
            "df = df.sort_values(['symbol', 'date']).reset_index(drop=True)\n",
            "\n",
            "print('rows:', len(df))\n",
            "print('date range:', df['date'].min().date(), '->', df['date'].max().date())\n",
            "df.groupby(['symbol', 'name']).agg(\n",
            "    rows=('date', 'size'),\n",
            "    start=('date', 'min'),\n",
            "    end=('date', 'max'),\n",
            "    first_close=('close', 'first'),\n",
            "    last_close=('close', 'last'),\n",
            ")\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def max_drawdown(equity: pd.Series) -> float:\n",
            "    drawdown = equity / equity.cummax() - 1\n",
            "    return float(drawdown.min())\n",
            "\n",
            "\n",
            "def annualized_return(equity: pd.Series) -> float:\n",
            "    total_return = equity.iloc[-1] / equity.iloc[0] - 1\n",
            "    years = (len(equity) - 1) / TRADING_DAYS\n",
            "    return float((1 + total_return) ** (1 / years) - 1)\n",
            "\n",
            "\n",
            "def annualized_sharpe(returns: pd.Series) -> float:\n",
            "    returns = returns.dropna()\n",
            "    std = returns.std(ddof=0)\n",
            "    if std == 0 or np.isnan(std):\n",
            "        return np.nan\n",
            "    return float(returns.mean() / std * np.sqrt(TRADING_DAYS))\n",
            "\n",
            "\n",
            "def calmar(ann_return: float, mdd: float) -> float:\n",
            "    if mdd >= 0 or np.isnan(mdd):\n",
            "        return np.nan\n",
            "    return float(ann_return / abs(mdd))\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "rows = []\n",
            "equity_curves = {}\n",
            "benchmark_rows = []\n",
            "benchmark_curves = {}\n",
            "\n",
            "for (symbol, name), g in df.groupby(['symbol', 'name'], sort=True):\n",
            "    g = g.sort_values('date').copy()\n",
            "    close = g['close'].astype(float)\n",
            "    asset_return = close.pct_change().fillna(0)\n",
            "    buy_hold_equity = (1 + asset_return).cumprod()\n",
            "    benchmark_curves[(symbol, name)] = pd.Series(buy_hold_equity.values, index=g['date'], name='buy_hold')\n",
            "    bench_ann = annualized_return(buy_hold_equity)\n",
            "    bench_mdd = max_drawdown(buy_hold_equity)\n",
            "    benchmark_rows.append({\n",
            "        'symbol': symbol,\n",
            "        'name': name,\n",
            "        'strategy': 'Buy & Hold',\n",
            "        'total_return': float(buy_hold_equity.iloc[-1] - 1),\n",
            "        'annualized_return': bench_ann,\n",
            "        'max_drawdown': bench_mdd,\n",
            "        'sharpe': annualized_sharpe(asset_return),\n",
            "        'calmar': calmar(bench_ann, bench_mdd),\n",
            "        'trades': 1,\n",
            "        'time_in_market': 1.0,\n",
            "    })\n",
            "\n",
            "    for window in WINDOWS:\n",
            "        sma = close.rolling(window).mean()\n",
            "        raw_signal = close > sma\n",
            "        position = raw_signal.shift(1).fillna(False).astype(float)\n",
            "        trade = position.diff().abs().fillna(position.abs())\n",
            "        strategy_return = position * asset_return - trade * FEE_RATE\n",
            "        equity = (1 + strategy_return).cumprod()\n",
            "        ann = annualized_return(equity)\n",
            "        mdd = max_drawdown(equity)\n",
            "        rows.append({\n",
            "            'symbol': symbol,\n",
            "            'name': name,\n",
            "            'sma_window': window,\n",
            "            'total_return': float(equity.iloc[-1] - 1),\n",
            "            'annualized_return': ann,\n",
            "            'max_drawdown': mdd,\n",
            "            'sharpe': annualized_sharpe(strategy_return),\n",
            "            'calmar': calmar(ann, mdd),\n",
            "            'trades': int(trade.sum()),\n",
            "            'time_in_market': float(position.mean()),\n",
            "        })\n",
            "        equity_curves[(symbol, name, window)] = pd.Series(equity.values, index=g['date'], name=f'SMA {window}')\n",
            "\n",
            "result = pd.DataFrame(rows)\n",
            "benchmark = pd.DataFrame(benchmark_rows)\n",
            "result\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "display_cols = ['symbol', 'name', 'sma_window', 'total_return', 'annualized_return', 'max_drawdown', 'sharpe', 'calmar', 'trades', 'time_in_market']\n",
            "display_result = result[display_cols].copy()\n",
            "for col in ['total_return', 'annualized_return', 'max_drawdown', 'time_in_market']:\n",
            "    display_result[col] = display_result[col].map(lambda x: f'{x:.2%}')\n",
            "for col in ['sharpe', 'calmar']:\n",
            "    display_result[col] = display_result[col].map(lambda x: f'{x:.3f}')\n",
            "display_result\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "benchmark_display = benchmark.copy()\n",
            "for col in ['total_return', 'annualized_return', 'max_drawdown', 'time_in_market']:\n",
            "    benchmark_display[col] = benchmark_display[col].map(lambda x: f'{x:.2%}')\n",
            "for col in ['sharpe', 'calmar']:\n",
            "    benchmark_display[col] = benchmark_display[col].map(lambda x: f'{x:.3f}')\n",
            "benchmark_display\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "stability = result.groupby(['symbol', 'name']).agg(\n",
            "    best_window=('sma_window', lambda s: int(result.loc[s.index].sort_values('total_return', ascending=False).iloc[0]['sma_window'])),\n",
            "    best_total_return=('total_return', 'max'),\n",
            "    worst_total_return=('total_return', 'min'),\n",
            "    median_total_return=('total_return', 'median'),\n",
            "    best_max_drawdown=('max_drawdown', 'max'),\n",
            "    worst_max_drawdown=('max_drawdown', 'min'),\n",
            "    min_trades=('trades', 'min'),\n",
            "    max_trades=('trades', 'max'),\n",
            ").reset_index()\n",
            "\n",
            "stability_display = stability.copy()\n",
            "for col in ['best_total_return', 'worst_total_return', 'median_total_return', 'best_max_drawdown', 'worst_max_drawdown']:\n",
            "    stability_display[col] = stability_display[col].map(lambda x: f'{x:.2%}')\n",
            "stability_display\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "fig, axes = plt.subplots(len(benchmark_curves), 1, figsize=(12, 10), sharex=False)\n",
            "if len(benchmark_curves) == 1:\n",
            "    axes = [axes]\n",
            "\n",
            "for ax, ((symbol, name), buy_hold) in zip(axes, benchmark_curves.items()):\n",
            "    buy_hold.plot(ax=ax, label='Buy & Hold', linewidth=2, color='black')\n",
            "    for window in WINDOWS:\n",
            "        equity_curves[(symbol, name, window)].plot(ax=ax, label=f'SMA {window}', alpha=0.75)\n",
            "    ax.set_title(f'{symbol} {name}')\n",
            "    ax.set_ylabel('Equity')\n",
            "    ax.legend(ncol=3, fontsize=8)\n",
            "    ax.grid(True, alpha=0.3)\n",
            "\n",
            "plt.tight_layout()\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 如何解读\n",
            "\n",
            "1. 如果 50/100/150/200/250 多数窗口表现方向一致，说明参数区间相对稳定。\n",
            "2. 如果只有一个窗口明显好，旁边窗口都差，要警惕参数过拟合。\n",
            "3. 如果 SMA 收益低于买入并持有，但最大回撤显著下降，它可能是风险控制工具，而不是收益增强工具。\n",
            "4. 如果交易次数很多、收益很薄，成本和滑点可能轻易吞掉结果。\n",
        ],
    },
]

for index, cell in enumerate(cells):
    cell["id"] = f"bt03-cell-{index:02d}"

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "pygments_lexer": "ipython3",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
NOTEBOOK_PATH.write_text(json.dumps(notebook, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Wrote {NOTEBOOK_PATH}")
